# Generated by Django 3.0.6 on 2020-05-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200527_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='balanse',
        ),
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
